language: python

python:
  - "3.6"

before_install:
  - cp secrets_dummy.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log

install:
  - pip3 install homeassistant

script:
  - hass -c . --script check_config
