#################################################################
## Adhan
#################################################################

  - alias: Adhan_start
    trigger:
      platform: time_pattern
      minutes: '/1'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.adhanaudio
          state: 'on'
        - condition: template
          value_template: '{{ (states.sensor.time.state == states.sensor.fajr.state) or (states.sensor.time.state == states.sensor.douhr.state) or (states.sensor.time.state == states.sensor.asr.state) or (states.sensor.time.state == states.sensor.maghrib.state) or (states.sensor.time.state == states.sensor.isha.state) }}'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.sony_speaker_3
          volume_level: '0.05'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.sony_speaker_3
          media_content_id: http://192.168.1.12:8123/local/adhan.mp3
          media_content_type: 'audio/mp3'

  - alias: Adhan_stop
    trigger:
      platform: state
      entity_id: input_boolean.adhanaudio
      from: 'on'
      to: 'off'
    action:
      service: media_player.media_stop
      data:
        entity_id: media_player.sony_speaker_3
