  - id: adhan_start
    alias: Adhan start
    trigger:
      platform: time_pattern
      minutes: '/1'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.adhanaudio
          state: 'on'
        - condition: template
          value_template: '{{ (states.sensor.time.state == states.sensor.fajr.state) or (states.sensor.time.state == states.sensor.douhr.state) or (states.sensor.time.state == states.sensor.asr.state) or (states.sensor.time.state == states.sensor.maghrib.state) or (states.sensor.time.state == states.sensor.isha.state) }}'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.sony_speaker_stereo
          volume_level: '0.05'
      - service: media_player.play_media
        data:
          entity_id: media_player.sony_speaker_stereo
          media_content_id: http://192.168.1.12:8123/local/adhan.mp3
          media_content_type: 'audio/mp3'

  - id: adhan_stop
    alias: Adhan stop
    trigger:
      platform: state
      entity_id: input_boolean.adhanaudio
      from: 'on'
      to: 'off'
    action:
      service: media_player.media_stop
      data:
        entity_id: media_player.sony_speaker_stereo

  - id: wakeup_automation
    alias: Wakeup automation
    trigger:
      platform: time_pattern
      minutes: '/1'
      seconds: 00
    condition:
      condition: or
      conditions:
        - condition: and
          conditions:
            - condition: template
              value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state  }}'
            - condition: state
              entity_id: input_boolean.alarmstatus
              state: 'on'
            - condition: state
              entity_id: input_boolean.alarmweekday
              state: 'on'
            - condition: time
              weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
        - condition: and
          conditions:
            - condition: template
              value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state  }}'
            - condition: state
              entity_id: input_boolean.alarmstatus
              state: 'on'
            - condition: state
              entity_id: input_boolean.alarmweekday
              state: 'off'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.bose_speaker
          volume_level: '0.15'
      - service: media_player.play_media
        data:
          entity_id: media_player.bose_speaker
          media_content_id: 4
          media_content_type: PLAYLIST
      - service: light.turn_on
        data:
          entity_id: light.lifx
      - delay: '00:00:30'
      - service: media_player.media_stop
        data:
          entity_id: media_player.bose_speaker
